language: python
python:
    - "3.3"

branches:
  only:
  - site
  
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq --no-install-recommends asciidoc

install:
    - pip install mynt
    
script: 
    - "ls -la"
    - mynt gen . output

