language: python

python:
  - "3.4"

env:
  global:
  - secure: "LlUvTKYutgxTzaLEfGRws8RBT3xh7qAG+CLEFdy7DR0EC2J/D8rlwP3fnoW267u6v3dCWey0iJ/ZlGH/Bk1lJ6jnp6vAjGBYGdIGzESjtYY0qvRWypimOeCc5y8Uw5d6qY8OdLcSS4+egExVDMLm6g18BPZKrd77kPSSlqY6krE="

branches:
  only:
    - site

cache: apt
sudo: false
addons:
    apt:
      packages:
        - language-pack-en-base
        - language-pack-es-base

before_install:
  - "pip install --upgrade pip wheel"

install:
    - pip install nikola
    - pip install webassets
    - git config --global user.email carlosvin@gmail.com
    - git config --global user.name carlosvin

script:
    - git checkout site > /dev/null
    - git clone --branch=master https://$GH_TOKEN@github.com/carlosvin/carlosvin.github.io.git output
    - nikola build
    - cd output
    - git add .
    - git commit . -m "Travis build pushed to master"
    - git pull
    - git push origin master 2> /dev/null
