language: python

branches:
  only:
    - master
    - site
    
install:
    - pip install pelican Markdown
    - git config --global user.email "carlosvin@gmail.com"
    - git config --global user.name "carlosvin"
    
script:
    - git checkout site
    - git clone --branch=master https://28012063f525c09496c176f1993b3f86a83eb16c@github.com/carlosvin/carlosvin.github.io.git output
    - ls output
    - pelican output
    - cd output
    - pwd
    - ls
    - git add .
    - git commit . -m "Travis build pushed to master"
    - git push origin master > /dev/null
