language: python
python:
    - "3.3"
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq --no-install-recommends asciidoc
 - sudo locale-gen es_ES.UTF-8 en_EN.UTF-8

install:
    - pip install .
    - pip install mynt
    
script: "ls -la"
