language: python
python:
    - "2.7"

branches:
  only:
    - master
    - site

install:
    - pip install nikola
    - git config --global user.email "carlosvin@gmail.com"
    - git config --global user.name "carlosvin"
    
script: 
    - git checkout site
    - git clone --depth=50 --branch=master git://github.com/carlosvin/carlosvin.github.io.git output
    - nikola build
    - cd output
    - git add .
    - git commit . -m "Travis build $TRAVIS_BUILD_NUMBER pushed to master"
    - pwd
    - git push origin master
