language: python
python:
    - "3.3"

branches:
  only:
    - site

install:
    - pip install nikola
    - git config --global user.email "carlosvin@gmail.com"
    - git config --global user.name "carlosvin"
    
script:
    - ls output > /dev/null
    - git clone --branch=master https://28012063f525c09496c176f1993b3f86a83eb16c@github.com/carlosvin/carlosvin.github.io.git output
    - ls output
    - nikola build
    - cd output
    - ls
    - git add .
    - git commit . -m "Travis build $TRAVIS_BUILD_NUMBER pushed to master"
    - pwd
    - git push origin master > /dev/null
