language: python
python:
    - "2.7"

install:
    - pip install nikola
    
script: 
    - git checkout site
    - git clone https://$(travis token)@github.com:carlosvin/carlosvin.github.io.git output
    - nikola build
    - cd output
    - git commit -m "Travis build $TRAVIS_BUILD_NUMBER pushed to master"
    - git push origin master
