language: python

env:
  global:
  - secure: "LlUvTKYutgxTzaLEfGRws8RBT3xh7qAG+CLEFdy7DR0EC2J/D8rlwP3fnoW267u6v3dCWey0iJ/ZlGH/Bk1lJ6jnp6vAjGBYGdIGzESjtYY0qvRWypimOeCc5y8Uw5d6qY8OdLcSS4+egExVDMLm6g18BPZKrd77kPSSlqY6krE="

branches:
  only:
    - site

before_install:
    - sudo apt-get update && sudo apt-get --reinstall install -qq language-pack-en language-pack-es

install:
    - sudo apt-get install libxml2-dev
    - sudo apt-get install libxslt1-dev
    - pip install nikola[extras]
    - git config --global user.email "$GIT_EMAIL"
    - git config --global user.name "$GIT_NAME"
    - nikola plugin -i iarchiver

script:
    - git checkout site > /dev/null
    - git clone --branch=master https://$GH_TOKEN@github.com/carlosvin/carlosvin.github.io.git output
    - cd output
    - git pull
    - ls -la
    - cd ..
    - nikola build
    - nikola iarchiver
    - cd output
    - ls -la
    - git add .
    - git commit . -m "Travis build pushed to master"
    - git push origin master 2> /dev/null
