language: python

env:
  global:
  - secure: "LlUvTKYutgxTzaLEfGRws8RBT3xh7qAG+CLEFdy7DR0EC2J/D8rlwP3fnoW267u6v3dCWey0iJ/ZlGH/Bk1lJ6jnp6vAjGBYGdIGzESjtYY0qvRWypimOeCc5y8Uw5d6qY8OdLcSS4+egExVDMLm6g18BPZKrd77kPSSlqY6krE="

branches:
  only:
    - site
    
addons:
  apt:
    packages:
    - language-pack-en
    - language-pack-es
    - libxml2-dev
    - libxslt1-dev

install:
    - pip install nikola[extras]
    - nikola plugin -i localsearch
    - nikola plugin -i ping
    - nikola install_theme zen

script:
    - git config --global user.email "$GIT_EMAIL"
    - git config --global user.name "$GIT_NAME"
    - git checkout site > /dev/null
    - git clone --branch=master https://$GH_TOKEN@github.com/carlosvin/carlosvin.github.io.git output
    - nikola build
    - nikola ping
    - cd output
    - ls -la
    - git add .
    - git config --global user.email carlosvin@gmail.com
    - git config --global user.name carlosvin
    - git commit . -m "Travis build pushed to master"
    - git push origin master 2> /dev/null
