language: python

env:
  global:
  - secure: "LlUvTKYutgxTzaLEfGRws8RBT3xh7qAG+CLEFdy7DR0EC2J/D8rlwP3fnoW267u6v3dCWey0iJ/ZlGH/Bk1lJ6jnp6vAjGBYGdIGzESjtYY0qvRWypimOeCc5y8Uw5d6qY8OdLcSS4+egExVDMLm6g18BPZKrd77kPSSlqY6krE="


branches:
  only:
    - site

before_install:
    - sudo apt-get update && sudo apt-get --reinstall install -qq language-pack-en language-pack-es

install:
    - pip install -r requirements.txt 
    - git config --global user.email "$GIT_EMAIL"
    - git config --global user.name "$GIT_NAME"

script:
    - git checkout site > /dev/null
    - git clone --branch=master https://$GH_TOKEN@github.com/carlosvin/carlosvin.github.io.git output
    - cd output
    - git pull
    - ls -la
    - cd ..
    - nikola build
    - cd output
    - ls -la
    - git add .
    - git commit . -m "Travis build pushed to master"
    - git push origin master
