language: python
python:
    - "3.3"
  
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq --no-install-recommends asciidoc

install:
    - pip install nikola
    
script: 
    - git checkout site
    - "ls -la"
    - nikola build
    - git checkout master
    - "ls -la"
