#
# BASE CONFIGURATION
#
base_url: /
domain:

#
# METADATA
#

# Used in header meta tags and the site feed. (required to generate a valid feed)
author: Carlos Martín Sánchez
# A description of your site to be used in header meta tags.
description: Carlos Website or Blog
# Used in the site feed.
email: carlosvin@gmail.com
# Your site's subtitle.
subtitle: Thoughts and ideas (good and bad)
# Your site's title. (required to generate a valid feed)
title: Vin's Blog


#
# THIRD PARTY SETTINGS
#

# If you'd like to enable Google Analytics for your site, set this to your tracking code.
analytics: UA-1328360-9


#
# Chances are you probably don't need to touch anything below here.
#

archive_layout: archive.html
archives_url: /archives/
tag_layout: tag.html
tags_url: /archives/

